name: Build Latest Image

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Login to GitHub Docker Registry
      run: docker login ghcr.io -u freyamade -p ${{ secrets.GITHUB_TOKEN }}
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag ghcr.io/freyamade/savageai-im/image:latest
    - name: Push the Docker image
      run: docker push ghcr.io/freyamade/savageai-im/image:latest
